name: Auto fix Markdown

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  auto-fix-markdown:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.OKP4_TOKEN }}

      - name: Lint markdown files
        uses: avto-dev/markdown-lint@v1.5.0
        continue-on-error: true
        with:
          args: "**/*.md"
          ignore: contracts/**/*.md contracts_versioned_docs/**/*.md modules/**/*.md modules_versioned_docs/**/*.md commands/**/*.md commands_versioned_docs/**/*.md
          fix: true

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: ${{ secrets.OKP4_BOT_GIT_COMMITTER_NAME }}
          commit_user_email: ${{ secrets.OKP4_BOT_GIT_COMMITTER_EMAIL }}
          commit_author: ${{ secrets.OKP4_BOT_GIT_AUTHOR_NAME }} <${{ secrets.OKP4_BOT_GIT_AUTHOR_EMAIL }}>
          commit_message: "style: autofix markdown files"
